### PR TITLE
[Experimental] Attempt to add automated versioning.

### PR DESCRIPTION
**Pull request by rexwangcc**
This PR is intending to add automated versioning provided by [`setuptools_scm`](https://github.com/pypa/setuptools_scm), so that we don't need to manually maintain `setup.py` and `conf.py`, which is painful and trivial.

### CODE REVIEW

**Comment by ambrosejcarr** [comment]
Seems like magic. How does it work?

**Comment by rexwangcc** [comment]
@ambrosejcarr I haven't looked into how does it work internally, but it will try to get the version in the order described here: https://github.com/pypa/setuptools_scm#default-versioning-scheme

**Comment by rexwangcc** [comment]
@ambrosejcarr Are you up for this? If not, I'm going to close this PR

**Comment by rexwangcc** [comment]
@ambrosejcarr This package works for installing from both PyPi and Github, but the prerequisite here is that you need to host your source code on Git-based platforms(Github, GitLab), and since at this moment, sctools is already on Github, I think it is fine.

I must say I haven't understood the full logic of the setuptools_scm, but I think it is worth trying it. And we can just remove it if there is anything bad in the future during the development process. What do you think?

**Comment by ambrosejcarr** [comment]
👍

**Pull request merged**
