### PR TITLE
Make explicit that sctools does not support python 3.5

### PR DESCRIPTION
**Pull request by ambrosejcarr**
We don't support this. Remove lines from setup.py.

### CODE REVIEW

**Comment by rexwangcc** [comment]
I don't know where I should put this comment, so let me comment on this PR... The docs build has been failing due to an outdated setuptools version. We need to either make sure readthedocs executes `pip install -U setuptools` or include the latest version of setuptools in requirements?

**Comment by ambrosejcarr** [comment]
> include the latest version of setuptools in requirements?

I'd give that a shot -- `readthedocs` has some defaults pre-installed that don't make any sense (e.g. old versions of `numpy`).

**Comment by ambrosejcarr** [comment]
^ This might also fix #52

**Comment by rexwangcc** [comment]
Merging this now

**Pull request merged**
